// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCK21xCR1JP1WxwS_u561JrNg6S83bdbt8',
    appId: '1:519858690666:web:484138f9e0f28750434813',
    messagingSenderId: '519858690666',
    projectId: 'om-sim-db',
    authDomain: 'om-sim-db.firebaseapp.com',
    storageBucket: 'om-sim-db.appspot.com',
    measurementId: 'G-4VGJT72Y01',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDoZwpB2yxjutZudh3QHkU1RfEK9tf8TXw',
    appId: '1:519858690666:android:349a2b53f7c0a647434813',
    messagingSenderId: '519858690666',
    projectId: 'om-sim-db',
    storageBucket: 'om-sim-db.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCMy4TOdlIZeIpQQVHOFDuyEXypYtfYzig',
    appId: '1:519858690666:ios:870c4c9d17581749434813',
    messagingSenderId: '519858690666',
    projectId: 'om-sim-db',
    storageBucket: 'om-sim-db.appspot.com',
    iosBundleId: 'com.example.omSalaryAndMembership',
  );
}
